### PR TITLE
Expose the `log` method from `CrashlyticsRecorder`

### PR DESCRIPTION
**Pull request by bpoplauschi**

### CODE REVIEW

**Comment by bpoplauschi** [comment]
I would appreciate a quick merge and a new version, as we are kind of blocked because of this.

**Comment by AnthonyMDev** [comment]
Whoops! Thats embarrassing, thanks for the PR. Will push a new version now.

**Comment by bpoplauschi** [comment]
@AnthonyMDev Many thanks.

**Comment by bpoplauschi** [comment]
PS: Nice way of solving the transitive dependency issue.

**Comment by AnthonyMDev** [comment]
@bpoplauschi Thanks! Glad to see someone getting some use from this!

**Pull request merged**
